Mgeek.Frontend/Controllers/AuthController.cs
namespace Mgeek.Frontend.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ITokenProvider _tokenProvider;
    
    public AuthController(IAuthService authService, ITokenProvider tokenProvider)
    {
        _authService = authService;
        _tokenProvider = tokenProvider;
    }
    
    [HttpGet]
    public IActionResult Login() => View(new LoginRequestDto());
    
    [HttpPost]
    public async Task<IActionResult> Login(LoginRequestDto model)
    {
        var responseDto = await _authService.LoginAsync(model);
        if (responseDto!.IsSuccess)
        {
            var loginResponseDto =
                JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result)!);
            
            await SignInUser(loginResponseDto!);
            _tokenProvider.SetToken(loginResponseDto!.Token!);
            return RedirectToAction("Index", "Home");
        }
        ViewBag.Message = responseDto!.Message! + "*";
        ModelState.AddModelError("AuthError", responseDto!.Message!);
        return View(model);
    } 
    
    [HttpGet]
    public IActionResult Register() => View();
    
    [HttpPost]
    public async Task<IActionResult> Register(RegistrationRequestDto model)
    {
        var responseDto = await _authService.RegisterAsync(model);
        if (responseDto!.IsSuccess)
        {
            var assignRole = await _authService.AssignRoleAsync(model);
            if (assignRole!.IsSuccess)
            {
                return RedirectToAction(nameof(Login));
            }
        }
        ViewBag.Message = responseDto!.Message! + "*";
        return View("Register");
    }
    
    [HttpGet]
    public IActionResult PersonalArea() => View();
    
    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        _tokenProvider.ClearToken();
        return RedirectToAction("Index", "Home");
    }

    private async Task SignInUser(LoginResponseDto model)
    {
        var handler = new JwtSecurityTokenHandler();
        var jwt = handler.ReadJwtToken(model.Token);

        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
        identity.AddClaim(new (JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(u=>u.Type== JwtRegisteredClaimNames.Email)!.Value));
        identity.AddClaim(new (JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(u=>u.Type== JwtRegisteredClaimNames.Sub)!.Value));
        identity.AddClaim(new (JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(u=>u.Type== JwtRegisteredClaimNames.Name)!.Value));
        
        identity.AddClaim(new (ClaimTypes.Name, jwt.Claims.FirstOrDefault(u=>u.Type== JwtRegisteredClaimNames.Email)!.Value));
        identity.AddClaim(new (ClaimTypes.Role, jwt.Claims.FirstOrDefault(u=>u.Type== "role")!.Value));
        
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
    }
}

Mgeek.Frontend/Controllers/CartController.cs
namespace Mgeek.Frontend.Controllers;

[Authorize]
public class CartController : Controller
{
    private readonly ICartService _cartSerivce;
    private readonly IToastNotification _notifications;

    public CartController(ICartService cartSerivce, IToastNotification toastNotification)
    {
        _cartSerivce = cartSerivce;
        _notifications = toastNotification;
    }

    [HttpGet]
    public async Task<IActionResult> CartIndex()
    {
        ViewBag.Message = TempData["Message"]!;
        
        var response = await _cartSerivce.GetCart();
        if (response!.IsSuccess)
        {
            return  View(JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result)!)!);
        }
        
        return View(new CartDto());
    }
    
    [HttpPost]
    public async Task<IActionResult> AddProductToCart(int productId)
    {
        var cartDetails = new CartDetailsDto { Count = 1, ProductId = productId };

        var cartDto = new CartDto
        {
            CartHeader = new CartHeaderDto()
            {
                UserId = User.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub)?.Value
            },
            CartDetails = new List<CartDetailsDto> { cartDetails }
        };
        
        var response = await _cartSerivce.UpsertCart(cartDto);

        if (response!.IsSuccess)
        {
            _notifications.AddSuccessToastMessage("Product successfully added to cart");
            return RedirectToAction(nameof(CartIndex));
        }

        return RedirectToAction("Error", "Home");
    }
    
    [HttpGet]
    public async Task<IActionResult> RemoveProduct(int cartDetailsId)
    {
        var response = await _cartSerivce.RemoveFromCart(cartDetailsId);
        _notifications.AddWarningToastMessage("Product removed from cart");
        return RedirectToAction(nameof(CartIndex));
    }
    
    [HttpPost]
    public async Task<IActionResult> UpdatePromo(CartDto cartDto)
    {
        cartDto.CartHeader!.UserId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
        var response = await _cartSerivce.ApplyPromo(cartDto);
        
        if(response!.IsSuccess)
            _notifications.AddSuccessToastMessage("Promo code successfully applied");
        else
            _notifications.AddWarningToastMessage(response.Message);
        
        TempData["Message"] = response!.Message!;
        return RedirectToAction(nameof(CartIndex));
    }
}

Mgeek.Frontend/Controllers/ProductController.cs
namespace Mgeek.Frontend.Controllers;

public class ProductController : Controller
{
    private readonly IProductService _productService;
    private readonly IToastNotification _notifications;

    public ProductController(IProductService productService, IToastNotification toastNotification)
    {
        _productService = productService;
        _notifications = toastNotification;
    }

    #region AdminPanelStock
    
    [HttpGet]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> StockIndex()
    {
        var response = await _productService.GetStocks();
        if (response!.IsSuccess)
        {
            var products = JsonConvert.DeserializeObject<List<StockDto>>(Convert.ToString(response.Result)!)!;
            return View(products.OrderBy(x => x.ProductId));
        }
        else
        {
            ViewBag.Message = "Product api doesn't work or products missing";
            return View();
        }
    }
    
    [HttpGet]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> StockUpdate(int productId)
    {
        var response = await _productService.GetStock(productId);
        if (response!.IsSuccess)
        {
            var product = JsonConvert.DeserializeObject<StockDto>(Convert.ToString(response.Result)!)!;
            return View(product);
        }
        else
        {
            ViewBag.Message = "Product api doesn't work or products missing";
            return View();
        }
    }

    [HttpPost]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> StockUpdate(StockDto stock)
    {
        var response = await _productService.StockUpdate(stock.ProductId, stock.Amount);
        
        if (response!.IsSuccess)
            _notifications.AddSuccessToastMessage("The quantity of goods in stock has been successfully updated");
        else
            _notifications.AddErrorToastMessage(response.Message);
        
        return RedirectToAction("StockIndex");
    }
    
    #endregion
    
    #region AdminPanelProduct
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> ProductIndex()
    {
        var response = await _productService.GetAll();
        if (response!.IsSuccess)
        {
            var products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(response.Result)!)!;
            return View(products.OrderBy(x=>x.Id));
        }
        else
        {
            ViewBag.Message = "Product api doesn't work or products missing";
            return View();
        }
    }
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        await _productService.Delete(id);
        _notifications.AddSuccessToastMessage($"Product with id {id} successfully deleted");
        return RedirectToAction("ProductIndex");
    }
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public IActionResult ChooseProduct() => View();
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> ChooseCreatePageForProduct(int id) 
    {
        var category = await GetCategory(id);
        return category switch
        {
            "Laptop" => RedirectToAction("LaptopCreate", new { id = id }),
            "Smartphone" => RedirectToAction("SmartphoneCreate", new { id = id }),
            _ => Content("Category of product not found")
        };
    }
    
    private async Task<string> GetCategory(int id)
    {
        var response = await _productService.GetCategoryById(id);
        return response!.Result!.ToString()!;
    }
    
    #endregion

    #region ProductDetail
    
    [HttpGet]
    public async Task<IActionResult> ChooseDetailPageForProduct(int id)
    {
        var category = await GetCategory(id);
        return category switch
        {
            "Laptop" => RedirectToAction("LaptopDetails", new { id = id }),
            "Smartphone" => RedirectToAction("SmartphoneDetails", new { id = id }),
            _ => Content("Category of product not found")
        };
    }
    
    [HttpGet]
    public async Task<IActionResult> SmartphoneDetails(int id)
    {
        var response = await _productService.GetById(id);
        var stockResponse = await _productService.GetStock(id);
        var stock = JsonConvert.DeserializeObject<StockDto>(Convert.ToString(stockResponse!.Result)!)!;
        SmartphoneVM smartphone = new()
        {
            SmartphoneDto = JsonConvert.DeserializeObject<SmartphoneDto>(Convert.ToString(response!.Result)!)!,
            Amount = stock.Amount
        };
        return View(smartphone);
    }
    
    [HttpGet]
    public async Task<IActionResult> LaptopDetails(int id)
    {
        var productResponse = await _productService.GetById(id);
        var stockResponse = await _productService.GetStock(id);
        var stock = JsonConvert.DeserializeObject<StockDto>(Convert.ToString(stockResponse!.Result)!)!;
        LaptopVM laptop = new()
        {
            LaptopDto = JsonConvert.DeserializeObject<LaptopDto>(Convert.ToString(productResponse!.Result)!)!,
            Amount = stock.Amount
        };
        return View(laptop);
    }
    
    #endregion

    #region Create 
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> LaptopCreate(int id)
    {
        if (id != 0)
        {
            var response = await _productService.GetById(id);
            var product = JsonConvert.DeserializeObject<LaptopDto>(Convert.ToString(response!.Result)!)!;
            return View(product);
        }

        return View();
    }

    [HttpPost]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> LaptopCreate(LaptopDto laptopDto)
    {
        var response = await _productService.LaptopUpsert(laptopDto);
        if(response!.IsSuccess == true)
            _notifications.AddSuccessToastMessage("Laptop added successfully");
        else
            _notifications.AddWarningToastMessage(response.Message);
        return RedirectToAction("ProductIndex");
    }

    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> SmartphoneCreate(int id)
    {
        if (id != 0)
        {
            var response = await _productService.GetById(id);
            var product = JsonConvert.DeserializeObject<SmartphoneDto>(Convert.ToString(response!.Result)!)!;
            return View(product);
        }
        return View();
    }

    [HttpPost]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> SmartphoneCreate(SmartphoneDto smartphoneDto)
    {
        var response = await _productService.SmartphoneUpsert(smartphoneDto);
        if(response!.IsSuccess == true)
            _notifications.AddSuccessToastMessage("Smartphone added successfully");
        else
            _notifications.AddWarningToastMessage(response.Message);
        return RedirectToAction("ProductIndex");
    }
    #endregion
}

Mgeek.Frontend/Views/Shared/_IndividualProductCard.cshtml
@model Mgeek.Frontend.Models.ProductAPI.ProductDto


<div class="col-xl-3 col-6 pb-4 product-card">
    <a asp-controller="Product" asp-action="ChooseDetailPageForProduct" asp-route-id="@Model.Id">
        <img class="img-fluid" src="@Model.ImageUrl" alt="Card image cap"/>
        <div class="row text-center">
            <div class="offset-xl-0 col-xl-12">
                <label>
                    <span class="text-black brand" style="margin-bottom: -40px; margin-left: 15px; font-weight: bold">@Model.Brand</span>
                </label>
            </div>
            <div class="offset-xl-0 col-xl-12">
                <label class="text-black" style="font-size: 15px; margin-left: 20px; color: grey">@Model.Name</label>
            </div>
            <div class="price offset-xl-0 col-xl-12">
                <label>
                    <span class="price" style="font-weight: bold; margin-left: 20px;">@Model.Price.ToString("c0")</span>
                </label>
            </div>
        </div>
    </a>
</div>

Mgeek.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Mgeek.Frontend</title>
    <link rel="stylesheet" href="~/css/notifications.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Mgeek.Frontend.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar-expand-xl navbar-toggleable-xl navbar-light border-bottom box-shadow mb-3" style="background-color: #6c4675">
        <!--navbar -->
        <div class="container-fluid">
            <div class="row col-xl-12">
                <div class="offset-xl-4 col-xl-4 text-center">
                    <a style="text-decoration: none" asp-controller="Home" asp-action="Index"><h1 style="font-size: 50px;" class="text-white mt-4 mt-xl-2">Mgeek</h1></a>
                </div>
                <div class="col-xl-4"></div>
            </div>
        </div>
        <div class="container">
            <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="col-xl-12 ">
                <div class="justify-content-center navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav">
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">
                                <h4 class="text-white">Smartphones</h4>
                            </a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">
                                <h4 class="text-white">Laptops</h4>
                            </a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">
                                <h4 class="text-white">Tablets</h4>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Cart" asp-action="CartIndex">
                                <h4 class="text-white">CART</h4>
                            </a>
                        </li>


                        @if (!User.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a style="text-transform: lowercase" class="nav-link text-white" asp-controller="Auth" asp-action="PersonalArea">
                                    <h4 class="text-white">Personal Area</h4>
                                </a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container-fluid">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Mgeek.Frontend
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
@await Component.InvokeAsync("NToastNotify")
</body>
</html>