Mgeek.Frontend/Controllers/CartController.cs
namespace Mgeek.Frontend.Controllers;

[Authorize]
public class CartController : Controller
{
    private readonly ICartService _cartSerivce;
    private readonly IToastNotification _notifications;

    public CartController(ICartService cartSerivce, IToastNotification toastNotification)
    {
        _cartSerivce = cartSerivce;
        _notifications = toastNotification;
    }

    [HttpGet]
    public async Task<IActionResult> CartIndex()
    {
        ViewBag.Message = TempData["Message"]!;
        
        var response = await _cartSerivce.GetCart();
        if (response!.IsSuccess)
        {
            return  View(JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result)!)!);
        }
        
        return View(new CartDto());
    }
    
    [HttpPost]
    public async Task<IActionResult> AddProductToCart(int productId)
    {
        var cartDetails = new CartDetailsDto { Count = 1, ProductId = productId };

        var cartDto = new CartDto
        {
            CartHeader = new CartHeaderDto()
            {
                UserId = User.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub)?.Value
            },
            CartDetails = new List<CartDetailsDto> { cartDetails }
        };
        
        var response = await _cartSerivce.UpsertCart(cartDto);

        if (response!.IsSuccess)
        {
            _notifications.AddSuccessToastMessage("Product successfully added to cart");
            return RedirectToAction(nameof(CartIndex));
        }

        return RedirectToAction("Error", "Home");
    }
    
    [HttpGet]
    public async Task<IActionResult> RemoveProduct(int cartDetailsId)
    {
        var response = await _cartSerivce.RemoveFromCart(cartDetailsId);
        _notifications.AddWarningToastMessage("Product removed from cart");
        return RedirectToAction(nameof(CartIndex));
    }
    
    [HttpPost]
    public async Task<IActionResult> UpdatePromo(CartDto cartDto)
    {
        cartDto.CartHeader!.UserId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
        var response = await _cartSerivce.ApplyPromo(cartDto);
        
        if(response!.IsSuccess)
            _notifications.AddSuccessToastMessage("Promo code successfully applied");
        else
            _notifications.AddWarningToastMessage(response.Message);
        
        TempData["Message"] = response!.Message!;
        return RedirectToAction(nameof(CartIndex));
    }
}

Mgeek.Frontend/Controllers/OrderController.cs
namespace Mgeek.Frontend.Controllers;

[Authorize]
public class OrderController : Controller
{
    private readonly IOrderService _orderService;
    private readonly ICartService _cartService;
    private readonly IMessageProducer _messageProducer;
    private readonly IToastNotification _notifications;
    public OrderController(IOrderService orderService, ICartService cartService, IMessageProducer messageProducer, IToastNotification notifications)
    {
        _orderService = orderService;
        _cartService = cartService;
        _messageProducer = messageProducer;
        _notifications = notifications;
    }

    [HttpGet]
    public IActionResult FoundOrders() => View();

    [HttpGet]
    public IActionResult OrderSuccess() => View();
    
    [HttpGet]
    public async Task<IActionResult> OrderIndex()
    {
        var response = await _orderService.GetOrderByUserId();
        if (response!.IsSuccess)
            return View(JsonConvert.DeserializeObject<List<OrderDto>>(Convert.ToString(response.Result)!)!);

        return  View(new List<OrderDto>());
    }

    [HttpGet]
    public async Task<IActionResult> OrderDetail(int orderId)
    {
        var response = await _orderService.GetOrder(orderId);
        if (response!.IsSuccess)
            return View(JsonConvert.DeserializeObject<OrderDto>(Convert.ToString(response.Result)!));

        _notifications.AddWarningToastMessage("Order deleted or not found");        
        return RedirectToAction("OrderIndex");
    }

    [HttpGet]
    public async Task<IActionResult> OrderCreate()
    {
        var cart = await LoadCart();
        if (cart.CartHeader == null)
            return RedirectToAction("CartIndex", "Cart");

        OrderVM orderVm = new() { Cart = cart };
        return View(orderVm);
    }

    [HttpPost]
    public async Task<IActionResult> OrderCreate(OrderVM orderVm)
    {
        orderVm.Cart = await LoadCart();

        List<OrderDetailsDto> orderDetails = new();
        foreach (var item in orderVm!.Cart!.CartDetails!)
        {
            OrderDetailsDto orderDetail = new()
            {
                ProductId = item.ProductId,
                Amount = item.Count
            };
            orderDetails.Add(orderDetail);
        }

        OrderDto orderDto = new OrderDto()
        {
            OrderHeaderDto = new()
            {
                UserId = orderVm.Cart!.CartHeader!.UserId,
                OrderDate = DateTime.Now,
                Address = orderVm.Address,
                Surname = orderVm.Surname,
                NumberPhone = orderVm.NumberPhone,
                Name = orderVm.Name,
                Sum = orderVm.Cart.CartHeader!.CartTotal,
                Promocode = orderVm.Cart.CartHeader.PromoCode,
                Status = "Under review"
            },
            OrderDetailsDto = orderDetails
        };
        await _cartService.RemoveCartPermanently();
        _messageProducer.SendingMessage<OrderDto>(orderDto);
        return RedirectToAction("OrderSuccess");
    }

    [HttpPost]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> FoundOrders(string numberPhone)
    {
        var response = await _orderService.GetOrdersByNumberPhone(numberPhone!);

        if (response!.IsSuccess)
        {
            var result = JsonConvert.DeserializeObject<List<OrderDto>>(Convert.ToString(response.Result)!)!;
            return View(result);
        }

        return View();
    }
    
    public async Task<IActionResult> DeleteOrder(int orderId)
    {
        var result = await _orderService.DeleteOrder(orderId);
        if (result!.IsSuccess)
            return RedirectToAction(nameof(OrderIndex));
        else
            return RedirectToAction("Error", "Home");
    }

    private async Task<CartDto> LoadCart()
    {
        var response = await _cartService.GetCart();
        if (response!.IsSuccess)
            return JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result)!)!;

        return new CartDto();
    }
}

Mgeek.Frontend/Controllers/ProductController.cs
namespace Mgeek.Frontend.Controllers;

public class ProductController : Controller
{
    private readonly IProductService _productService;
    private readonly IToastNotification _notifications;

    public ProductController(IProductService productService, IToastNotification toastNotification)
    {
        _productService = productService;
        _notifications = toastNotification;
    }

    #region AdminPanelStock
    
    [HttpGet]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> StockIndex()
    {
        var response = await _productService.GetStocks();
        if (response!.IsSuccess)
        {
            var products = JsonConvert.DeserializeObject<List<StockDto>>(Convert.ToString(response.Result)!)!;
            return View(products.OrderBy(x => x.ProductId));
        }
        else
        {
            ViewBag.Message = "Product api doesn't work or products missing";
            return View();
        }
    }
    
    [HttpGet]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> StockUpdate(int productId)
    {
        var response = await _productService.GetStock(productId);
        if (response!.IsSuccess)
        {
            var product = JsonConvert.DeserializeObject<StockDto>(Convert.ToString(response.Result)!)!;
            return View(product);
        }
        else
        {
            ViewBag.Message = "Product api doesn't work or products missing";
            return View();
        }
    }

    [HttpPost]
    [Authorize(Roles = WC.RoleAdmin)]
    public async Task<IActionResult> StockUpdate(StockDto stock)
    {
        var response = await _productService.StockUpdate(stock.ProductId, stock.Amount);
        
        if (response!.IsSuccess)
            _notifications.AddSuccessToastMessage("The quantity of goods in stock has been successfully updated");
        else
            _notifications.AddErrorToastMessage(response.Message);
        
        return RedirectToAction("StockIndex");
    }
    
    #endregion
    
    #region AdminPanelProduct
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> ProductIndex()
    {
        var response = await _productService.GetAll();
        if (response!.IsSuccess)
        {
            var products = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(response.Result)!)!;
            return View(products.OrderBy(x=>x.Id));
        }
        else
        {
            ViewBag.Message = "Product api doesn't work or products missing";
            return View();
        }
    }
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        await _productService.Delete(id);
        _notifications.AddSuccessToastMessage($"Product with id {id} successfully deleted");
        return RedirectToAction("ProductIndex");
    }
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public IActionResult ChooseProduct() => View();
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> ChooseCreatePageForProduct(int id) 
    {
        var category = await GetCategory(id);
        return category switch
        {
            "Laptop" => RedirectToAction("LaptopCreate", new { id = id }),
            "Smartphone" => RedirectToAction("SmartphoneCreate", new { id = id }),
            _ => Content("Category of product not found")
        };
    }
    
    private async Task<string> GetCategory(int id)
    {
        var response = await _productService.GetCategoryById(id);
        return response!.Result!.ToString()!;
    }
    
    #endregion

    #region ProductDetail
    
    [HttpGet]
    public async Task<IActionResult> ChooseDetailPageForProduct(int id)
    {
        var category = await GetCategory(id);
        return category switch
        {
            "Laptop" => RedirectToAction("LaptopDetails", new { id = id }),
            "Smartphone" => RedirectToAction("SmartphoneDetails", new { id = id }),
            _ => Content("Category of product not found")
        };
    }
    
    [HttpGet]
    public async Task<IActionResult> SmartphoneDetails(int id)
    {
        var response = await _productService.GetById(id);
        var stockResponse = await _productService.GetStock(id);
        var stock = JsonConvert.DeserializeObject<StockDto>(Convert.ToString(stockResponse!.Result)!)!;
        SmartphoneVM smartphone = new()
        {
            SmartphoneDto = JsonConvert.DeserializeObject<SmartphoneDto>(Convert.ToString(response!.Result)!)!,
            Amount = stock.Amount
        };
        return View(smartphone);
    }
    
    [HttpGet]
    public async Task<IActionResult> LaptopDetails(int id)
    {
        var productResponse = await _productService.GetById(id);
        var stockResponse = await _productService.GetStock(id);
        var stock = JsonConvert.DeserializeObject<StockDto>(Convert.ToString(stockResponse!.Result)!)!;
        LaptopVM laptop = new()
        {
            LaptopDto = JsonConvert.DeserializeObject<LaptopDto>(Convert.ToString(productResponse!.Result)!)!,
            Amount = stock.Amount
        };
        return View(laptop);
    }
    
    #endregion

    #region Create 
    
    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> LaptopCreate(int id)
    {
        if (id != 0)
        {
            var response = await _productService.GetById(id);
            var product = JsonConvert.DeserializeObject<LaptopDto>(Convert.ToString(response!.Result)!)!;
            return View(product);
        }

        return View();
    }

    [HttpPost]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> LaptopCreate(LaptopDto laptopDto)
    {
        var response = await _productService.LaptopUpsert(laptopDto);
        if(response!.IsSuccess == true)
            _notifications.AddSuccessToastMessage("Laptop added successfully");
        else
            _notifications.AddWarningToastMessage(response.Message);
        return RedirectToAction("ProductIndex");
    }

    [HttpGet]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> SmartphoneCreate(int id)
    {
        if (id != 0)
        {
            var response = await _productService.GetById(id);
            var product = JsonConvert.DeserializeObject<SmartphoneDto>(Convert.ToString(response!.Result)!)!;
            return View(product);
        }
        return View();
    }

    [HttpPost]
    [Authorize(Roles=WC.RoleAdmin)]
    public async Task<IActionResult> SmartphoneCreate(SmartphoneDto smartphoneDto)
    {
        var response = await _productService.SmartphoneUpsert(smartphoneDto);
        if(response!.IsSuccess == true)
            _notifications.AddSuccessToastMessage("Smartphone added successfully");
        else
            _notifications.AddWarningToastMessage(response.Message);
        return RedirectToAction("ProductIndex");
    }
    #endregion
}

Mgeek.Frontend/Views/Cart/CartIndex.cshtml
@model Mgeek.Frontend.Models.CartAPI.CartDto

@if (Model.CartDetails != null && Model.CartDetails.Any())
{
    <form method="post">
        <div class="container">
            <div class="col-xl-12">
                <div class="row">
                    <div class="col-xl-1">

                    </div>
                    <div class="col-xl-1 col-2">
                        <h1 class="mt-1 mx-xl-4">Cart</h1>
                    </div>
                    <div class="col-xl-10 col-8 mt-xl-0 mt-3 mx-3 mx-xl-0">
                        @{
                            int amountProduct = 0;
                            @foreach (var item in Model.CartDetails!)
                            {
                                amountProduct += item.Count;
                            }
                        }
                        <h6 class="mt-xl-4 mx-xl-3">@amountProduct product, @($"{Model.CartHeader!.Discount + Model.CartHeader!.CartTotal:c}")</h6>
                    </div>
                </div>
                @foreach (var item in Model.CartDetails!)
                {
                    <div class="row mt-3 mt-xl-0">
                        <div class="col-xl-1">

                        </div>
                        <div class="col-xl-8 col-12">
                            <div class="card border-0">
                                <div class="row">
                                    <div class="col-xl-3 mt-xl-3 mb-xl-3 col-4">
                                        <a style="text-decoration: none" asp-controller="Product" asp-action="ChooseDetailPageForProduct" asp-route-id="@item.Product!.Id">
                                            <img src="@item.Product!.ImageUrl" class="rounded" width="100%"/>
                                        </a>
                                    </div>
                                    <div class="col-xl-9 mt-xl-3 col-8 mt-3">
                                        <a style="text-decoration: none" asp-controller="Product" asp-action="ChooseDetailPageForProduct" asp-route-id="@item.Product!.Id">
                                            <h4 class="mt-xl-2" style="color: black">@item.Product.Name</h4>
                                        </a>
                                        <h6 class="mt-xl-4 d-none d-sm-block">@(item.Product!.Description!.Substring(0, Math.Min(item.Product.Description.Length, 350)))...</h6>
                                        <h4 class="mt-xl-4" style="color:black">@($"{item.Product.Price:c}") x @item.Count</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 d-none d-sm-block">
                            <div>ㅤ</div>
                            <a asp-action="RemoveProduct" asp-route-cartDetailsId="@item.Id">
                                <img class="mt-xl-5 mx-xl-4 " src="https://imagess.hb.ru-msk.vkcs.cloud/trash_bin_icon-icons.com_67981.png" width="10%"/>
                            </a>
                        </div>
                    </div>
                }
            </div>
            <div class="row mt-xl-3">
                <div class="col-xl-1">

                </div>
                <div class="col-xl-5 mt-xl-0 mt-3">
                    <div class="row">
                        <div class="card" style="background-color: #6c4675">
                            <div class="col-xl-12 ">
                                <h4 class="text-white text-center mt-3">use promo-code: </h4>
                            </div>
                            <div class="col-xl-12 mb-xl-0 mb-3">
                                <input style="background-color: transparent; border-top: none; font-size: 20px; border-left: none; border-right: none; color: white; outline: none; border-bottom-color: white" asp-for="CartHeader!.PromoCode" class="w-100 mt-xl-1"/>
                                <h6 class="text-white mt-xl-2">@ViewBag.Message</h6>
                            </div>
                            <div class="col-xl-12">
                                <button type="submit" asp-action="UpdatePromo" class="w-100 btn btn-outline-light text-center mt-xl-1 mb-xl-3 mb-3">Activate</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-4 card border-0 mt-xl-4 mt-3">
                    @if (Model.CartHeader.PromoCode != "")
                    {
                        <h4 class="text-success">Discount: @($"{Model.CartHeader!.Discount:c}")</h4>
                    }
                    <h3 class="text-black">Total Sum: @($"{Model.CartHeader!.CartTotal:c}")</h3>
                    <h6>Shipping cost not included*</h6>

                    <a asp-controller="Order" asp-action="OrderCreate" class="btn btn-outline-primary text-center">to Checkout</a>
                </div>
            </div>

        </div>
    </form>
}
else
{
    <div class="container text-center ">
        <div class="row">
            <h1 class="mt-xl-2">your shopping cart is empty :c</h1>
            <a style="text-decoration: none" asp-controller="Home" asp-action="Index"><h4 class="text-success">continue shopping</h4></a>
        </div>

    </div>
}